In [2]:
import numpy as np
import numpy.linalg as la


Exersice A

In [35]:
mat = np.array([[0, 1,], [-0.5, 1.5],[1.5, 2.5], [1, 3]])
mean = np.mean(mat, axis=0)
mat = mat - mean
print("\nMean:\n")
print(mat)
covMatrix = np.cov(mat)
print ("\nCoveriance Matrix:\n")
print (covMatrix)
w, v = la.eig(covMatrix)
print ("\nEeigen values:\n")
print(w)


Mean:

[[-0.5 -1. ]
 [-1.  -0.5]
 [ 1.   0.5]
 [ 0.5  1. ]]

Coveriance Matrix:

[[ 0.125 -0.125  0.125 -0.125]
 [-0.125  0.125 -0.125  0.125]
 [ 0.125 -0.125  0.125 -0.125]
 [-0.125  0.125 -0.125  0.125]]

Eeigen values:

[-5.55111512e-17  5.00000000e-01  0.00000000e+00  0.00000000e+00]
